|:------------------------:|:----------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|          Tática          |                                      Técnica                                       |                                                                                                  Detalhes                                                                                                 |
|:------------------------:|:----------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|      Acesso Inicial      |                         Phishing: Spearphishing (1566.001)                         |                                       Utilização de e-mails phishing   para empresas específicas (spearphishing) para realizar o download de trojans   ou loaders.                                        |
|                          |              Exploração   de aplicação voltado para o público (T1190)              |                                                                          Exploração de vulnerabilidades de   serviços públicos.                                                                           |
|                          |                              Contas   válidas (T1078)                              |                                                                         Utilização de contas comprometidas   para acesso via RDP.                                                                         |
|:------------------------:|:----------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|         Execução         |                                 API nativa (T1106)                                 |                                                                       Utilização de API nativa para   executar comandos e rotinas.                                                                        |
|                          |                    Comandos   e Interpretador de Scripts (T1059)                   |                                                  Utilização de interpretadores de   script como, Shell de comando do Windows, Visual Basic e PowerShell.                                                  |
|                          |                            Execução   do usuário (T1204)                           |                                                           Execução do usuário para realizar   a execução do payload ou link/anexos do phishing.                                                           |
|:------------------------:|:----------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|       Persistência       |               Inicialização automática ou   execução de logon (T1547)              |                                                                    Manipulação de registro para   execução do ransomware como serviço.                                                                    |
|                          |     Criar   ou modificar processo do sistema: Serviços do Windows. (T1543.003)     |                                                                        Criar um determinado serviço para   execução do ransomware.                                                                        |
|:------------------------:|:----------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| Escalação de privilégios |               Modificação de Política de Domínio   ou GPO (T1484.001)              |                            Utilização de credenciais roubadas   para acesso a servidores AD para obtenção de privilégios de administrador e   atacar outras máquinas na rede.                             |
|                          |               Exploração   para escalonamento de privilégios (T1068)               |                                                                      Utilização de vulnerabilidades   para escalação de privilégios.                                                                      |
|                          |                      Fluxo de   execução do sequestro (T1574)                      |                                                                                          Ignora a verificação UAC                                                                                         |
|:------------------------:|:----------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|     Evasão de Defesa     |              Mascaramento: assinatura de código   inválida (T1036.001)             |                                                                          Utilização de assinaturas   digitais: DVERI, FADO e TOV.                                                                         |
|                          |     Prejudica   as defesas por meio de desabilitação de ferramenta. (T1562.001)    |                                                                     Desativa o software de segurança,   realizando o seu encerramento.                                                                    |
|                          |              Desofuscar/Decodificar   arquivos ou informações (T1140)              |                                                         Aferramenta utilizada para   exfiltração de dados descarta um arquivo codificado em base64                                                        |
|                          |          Remoção   do indicador do host: exclusão do arquivo. (T1070.004)          |                                                                          Exclui os vestígios de si mesmo na   máquina infectada.                                                                          |
|                          |                 Injeção   de processos: Injeção de DLL (T1055.001)                 |                                                                          Injeção de carga para outras   ferramentas ou malwares.                                                                          |
|                          |                       Execução   de comando indireto (T1202)                       |                                                   Utiliza um script de inicialização   antes que o sistema chegue a tela de login por meio do registro.                                                   |
|                          | Remoção   do indicador no host: Limpeza do logs de eventos do Windows. (T1070.001) |                                                                                  Limpeza do log de eventos do   Windows.                                                                                  |
|:------------------------:|:----------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|        Descoberta        |                    Descoberta de arquivos e   diretórios (T1083)                   |                                                               Procura arquivos específicos e o   diretório relacionado à sua criptografia.                                                                |
|                          |                       Descoberta   do sistema remoto (T1018)                       |                                                                           Utilização de ferramentas para   varreduras de rede.                                                                            |
|                          |                          Descoberta   de processos (T1057)                         |                                                                           Descobre determinados processos   para encerramento.                                                                            |
|                          |                   Descoberta   de informações do sistema (T1082)                   |                                                                     Identifica o layout do teclado e   outras informações do sistema.                                                                     |
|                          |                           Registro   de consulta (T1012)                           |                                                                        Consulta determinados registros   como parte de sua rotina.                                                                        |
|                          |                    Descoberta   do software de segurança (T1063)                   |                                                             Descobre o software utilizado para   segurança para postermiormente interrompê-lo                                                             |
|:------------------------:|:----------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|   Movimentação Lateral   |                       Transferência de ferramentas   (T1570)                       |                                                                  Utiliza o RDP para baixar o   ransomware ou outras ferramentas na rede.                                                                  |
|                          |      Serviços   remotos: compartilhamentos administrativos via SMB (T1021.002)     |                                      Utiliza uma cópia do payload no AD   comprometido e em seguida cria um serviço na máquina de destino para executar   o payload.                                      |
|:------------------------:|:----------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|          Coleção         |                              Dados do Sistema. (T1005)                             |                                                      Utiliza o RDP para pesquisar   manualmente arquivos ou informações valiosas para os operadores.                                                      |
|:------------------------:|:----------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|   Comando   e Controle   |                     Protocolo na camada de aplicação   (T1071)                     |                                                                          Utiliza http/s para comunicação   com os servidores C&C                                                                          |
|:------------------------:|:----------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|        Exfiltração       |                      Exfiltração por serviço da web   (T1567)                      | Utiliza o shell da web DEWMODE e   extrai a lista de arquivos disponíveis de banco de dados “MySQL” de uma   aplicação. Bem como dos arquivos que se encontram armazenados e reunídos para   exfiltração. |
|:------------------------:|:----------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
|          Impacto         |                     Dados criptografados para impacto   (T1486)                    |                                                         Criptografia dos arquivos por meio   dos algoritmos de criptografia Salsa20, AES e ECDH.                                                          |
|                          |                      Inibe a   recuperação do sistema (T1490)                      |                                                                               Exclusão das cópias de sombras de   volumes.                                                                                |
|:------------------------:|:----------------------------------------------------------------------------------:|:---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------:|
